#!/bin/bash

./Bin/Debug/search ./TestData/01_test.xml
./Bin/Debug/search ./TestData/02_test.xml
./Bin/Debug/search ./TestData/03_test.xml
./Bin/Debug/search ./TestData/04_test.xml
./Bin/Debug/search ./TestData/05_test.xml
./Bin/Debug/search ./TestData/06_test.xml
./Bin/Debug/search ./TestData/07_test.xml
./Bin/Debug/search ./TestData/08_test.xml
./Bin/Debug/search ./TestData/09_test.xml
./Bin/Debug/search ./TestData/10_test.xml
./Bin/Debug/search ./TestData/11_test.xml
./Bin/Debug/search ./TestData/12_test.xml
./Bin/Debug/search ./TestData/13_test.xml
./Bin/Debug/search ./TestData/14_test.xml
./Bin/Debug/search ./TestData/15_test.xml
./Bin/Debug/search ./TestData/16_test.xml
./Bin/Debug/search ./TestData/17_test.xml
./Bin/Debug/search ./TestData/18_test.xml
./Bin/Debug/search ./TestData/19_test.xml
./Bin/Debug/search ./TestData/20_test.xml
./Bin/Debug/search ./TestData/21_test.xml
./Bin/Debug/search ./TestData/22_test.xml
./Bin/Debug/search ./TestData/23_test.xml
./Bin/Debug/search ./TestData/24_test.xml
./Bin/Debug/search ./TestData/25_test.xml
./Bin/Debug/search ./TestData/26_test.xml
./Bin/Debug/search ./TestData/27_test.xml
./Bin/Debug/search ./TestData/28_test.xml
./Bin/Debug/search ./TestData/29_test.xml
./Bin/Debug/search ./TestData/30_test.xml
./Bin/Debug/search ./TestData/31_test.xml
./Bin/Debug/search ./TestData/32_test.xml
./Bin/Debug/search ./TestData/33_test.xml
./Bin/Debug/search ./TestData/34_test.xml
./Bin/Debug/search ./TestData/35_test.xml
./Bin/Debug/search ./TestData/36_test.xml
./Bin/Debug/search ./TestData/37_test.xml
./Bin/Debug/search ./TestData/38_test.xml
./Bin/Debug/search ./TestData/39_test.xml
./Bin/Debug/search ./TestData/40_test.xml
./Bin/Debug/search ./TestData/41_test.xml
./Bin/Debug/search ./TestData/42_test.xml
./Bin/Debug/search ./TestData/43_test.xml
./Bin/Debug/search ./TestData/44_test.xml
